### ISSUE TITLE
能不能提供一个比较完整的demo?

### ISSUE THREAD

**Issue by yz1311** [dpzxsm/wepy-redux#2]
发现wepy中redux的使用还是跟react差别较大，能不能提供一个比较完整的demo?

**Comment by dpzxsm** [comment]
@yz1311  可以，我这个框架就是因为公司需要把react项目的redux状态管理迁移到小程序上而写的，近几天会写个demo

**Comment by dpzxsm** [comment]
更新了文档，也简单了写了一个Demo。最近比较闲，如果又不懂尽管来问我。顺便求一个Star。
