### ISSUE TITLE
computed 依赖导致报错 

### ISSUE THREAD

**Issue by songguangyu** [dpzxsm/wepy-redux#4]
我自己写了一个computed 属性 依赖于 connect的属性 
connect 的属性会提前塞到 computed里 wepy初始化的时候会执行 计算属性 这时候就导致报错
为什么不能把属性放到 data里

**Comment by dpzxsm** [comment]
@songguangyu  如果直接写到data中，由于wepy的机制，可能会直接触发渲染函数。但写到computed可以在渲染时候再写入data中，所以才要这样写。不过确实这里写的有问题，其实可以先把connnect中的属性先计算完再去计算自己写的computed，这样你就可以拿到值了，我马上就修复这个问题。

**Comment by dpzxsm** [comment]
@songguangyu  已经修复这个bug了，你重新试试？

**Comment by songguangyu** [comment]
@dpzxsm 
我把这个bug 提给了 wepy。 还有一种情况 就是 
```
 computed = {
    a () {
      return this.b + 1
    },
    b() {
     return 2
    }
 }
```
这种请求下  wepy 先执行 a()的时候 就会报错  找不到 this.b

**Comment by dpzxsm** [comment]
@songguangyu  wepy 的computed是这样子的，你要把b放在前面

**Comment by dpzxsm** [comment]
这样计算a的时候就能拿到b了，这个其实不能说是wepy的bug，本来就是这样的机制

**Comment by songguangyu** [comment]
那我 一个是connect 的 一个是我自己写的wepy 我怎么保证我的顺序 
```
@connect({
 a() { 
   return 1
 }
})
computed = {
    b () {
      return this.a + 1
    }
 }
```
这种情况呢？ 我觉得不应该说就是这样的机制吧  wepy 就是简单的for in了一下  实现的太简单（或者说有问题）

**Comment by dpzxsm** [comment]
@songguangyu  这种情况在第一次渲染时候是拿不到的，你可以去看wepy源码，computed的实现，和for in 差不多，就是对象遍历赋值给data的。这个是wepy作者没有考虑到的问题，我建议你自己维护一个redux链接库，不要用官方的，作者很久不维护了。

**Comment by dpzxsm** [comment]
哈哈，其实也可以用我这个库，刚刚已经解决你的这个问题了

**Comment by songguangyu** [comment]
我就是看了源码才觉得他实现的有问题  相对于vue来说
